dataset:
  name: 'qm9'            # qm9, qm9_positional
  datadir: 'data/qm9_midi'
  remove_h: False
  random_subset: null
  pin_memory: False
  adaptive_loader: False

train:
  # Training settings
  n_epochs: 1000

  batch_size: 1
  reference_batch_size: 300
  lr: 0.0002
  clip_grad: null          # float, null to disable
  save_model: True
  num_workers: 0
  ema_decay: 0           # 'Amount of EMA decay, 0 means off. A reasonable value  is 0.999.'
  progress_bar: false
  weight_decay: 1e-12
  scheduler: null #
  seed: 0

general:
  # General settings
  name: 'graph-tf-model'                   # Warning: 'debug' and 'test' are reserved name that have a special behavior

  wandb: 'online'                # online | offline | disabled
  gpus: 1                     # Multi-gpu is currently not implemented

  resume: null            # If resume, path to ckpt file from outputs directory in main directory
  test_only: null         # Use absolute path

  check_val_every_n_epochs: 5
  sample_every_val: 2
  val_check_interval: null
  samples_to_generate: 1024
  samples_to_save: 20
  chains_to_save: 1
  log_every_steps: 50
  number_chain_steps: 50        # Number of frames in each gif

  faster_sampling: 1                              # At each sampling step, set s=t-faster sampling (1 for normal sampling)

  final_model_samples_to_generate: 10000
  final_model_samples_to_save: 10
  final_model_chains_to_save: 5

  cpus_per_gpu: 4
  force_ray: false

  evaluate_all_checkpoints: False
  num_final_sampling: 5